import { openapi } from "@/lib/openapi";

/**
 * OpenAPI pages are generated by `fumadocs-openapi` and contain no prose — their
 * body is just an `<APIPage document="..." operations={...} />` element, which
 * disappears when the MDX is processed to plain Markdown.
 *
 * To keep `<page>.mdx` useful for LLMs, the operations referenced by the page are
 * rendered back to Markdown here, straight from the bundled OpenAPI schema.
 */

type JsonValue = string | number | boolean | null | JsonValue[] | JsonObject;

interface JsonObject {
  [key: string]: JsonValue | undefined;
}

interface OperationRef {
  path: string;
  method: string;
}

interface WebhookRef {
  name: string;
  method: string;
}

/** Nesting depth of object properties included in the output. */
const MAX_DEPTH = 5;

function isObject(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function asString(value: JsonValue | undefined): string | undefined {
  return typeof value === "string" ? value : undefined;
}

function asArray(value: JsonValue | undefined): JsonValue[] {
  return Array.isArray(value) ? value : [];
}

/** Collapse a Markdown description into a single line, for use inside a bullet. */
function inline(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function resolvePointer(doc: JsonObject, ref: string): JsonObject | undefined {
  let current: JsonValue | undefined = doc;

  for (const segment of ref.slice(2).split("/")) {
    const key = decodeURIComponent(segment)
      .replace(/~1/g, "/")
      .replace(/~0/g, "~");

    if (!isObject(current)) return undefined;
    current = current[key];
  }

  return isObject(current) ? current : undefined;
}

/**
 * Follow `$ref` pointers within the bundled document. Sibling keywords take
 * precedence over the target, matching how OpenAPI 3.1 merges them.
 */
function resolve(
  doc: JsonObject,
  node: JsonValue | undefined,
): JsonObject | undefined {
  let current = node;
  const seen = new Set<string>();

  while (isObject(current)) {
    const ref = asString(current.$ref);
    if (!ref?.startsWith("#/") || seen.has(ref)) break;
    seen.add(ref);

    const target = resolvePointer(doc, ref);
    if (!target) break;

    const merged: JsonObject = { ...target };
    for (const [key, value] of Object.entries(current)) {
      if (key !== "$ref") merged[key] = value;
    }
    current = merged;
  }

  return isObject(current) ? current : undefined;
}

function typeName(
  doc: JsonObject,
  schema: JsonObject | undefined,
  depth = 0,
): string {
  if (!schema || depth > 3) return "unknown";

  for (const [keyword, separator] of [
    ["oneOf", " | "],
    ["anyOf", " | "],
    ["allOf", " & "],
  ] as const) {
    const branches = asArray(schema[keyword]);
    if (branches.length > 0) {
      return branches
        .map((branch) => typeName(doc, resolve(doc, branch), depth + 1))
        .join(separator);
    }
  }

  const values = asArray(schema.enum);
  if (values.length > 0)
    return values.map((v) => JSON.stringify(v)).join(" | ");
  if (schema.const !== undefined) return JSON.stringify(schema.const);

  const type = schema.type;
  const types = Array.isArray(type)
    ? type.filter((v): v is string => typeof v === "string")
    : typeof type === "string"
      ? [type]
      : [];

  if (types.includes("array")) {
    return `${typeName(doc, resolve(doc, schema.items), depth + 1)}[]`;
  }

  if (types.length === 0) {
    return isObject(schema.properties) ? "object" : "unknown";
  }

  const format = asString(schema.format);
  return format ? `${types.join(" | ")}<${format}>` : types.join(" | ");
}

/**
 * Render a schema as a nested bullet list of its properties.
 */
function schemaLines(
  doc: JsonObject,
  schema: JsonObject | undefined,
  indent = "",
  depth = 0,
  branch: JsonObject[] = [],
): string[] {
  if (!schema || depth > MAX_DEPTH || branch.includes(schema)) return [];
  const nested = [...branch, schema];

  const properties = isObject(schema.properties)
    ? schema.properties
    : undefined;
  if (properties) {
    const required = new Set(
      asArray(schema.required).filter(
        (v): v is string => typeof v === "string",
      ),
    );
    const lines: string[] = [];

    for (const [name, value] of Object.entries(properties)) {
      const property = resolve(doc, value);
      const flags = [typeName(doc, property)];
      if (required.has(name)) flags.push("required");
      const description = asString(property?.description);

      lines.push(
        `${indent}- \`${name}\` (${flags.join(", ")})${
          description ? ` — ${inline(description)}` : ""
        }`,
      );
      lines.push(
        ...schemaLines(doc, property, `${indent}  `, depth + 1, nested),
      );
    }

    return lines;
  }

  const items = resolve(doc, schema.items);
  if (items) return schemaLines(doc, items, indent, depth + 1, nested);

  for (const keyword of ["oneOf", "anyOf", "allOf"] as const) {
    const branches = asArray(schema[keyword]);
    if (branches.length === 0) continue;

    return branches.flatMap((entry) =>
      schemaLines(doc, resolve(doc, entry), indent, depth + 1, nested),
    );
  }

  return [];
}

function contentLines(
  doc: JsonObject,
  content: JsonValue | undefined,
): string[] {
  if (!isObject(content)) return [];
  const lines: string[] = [];

  for (const [mediaType, value] of Object.entries(content)) {
    const media = resolve(doc, value);
    const schema = resolve(doc, media?.schema);

    lines.push("", `\`${mediaType}\`:`, "");
    const body = schemaLines(doc, schema);
    lines.push(
      ...(body.length > 0 ? body : [`- \`${typeName(doc, schema)}\``]),
    );
  }

  return lines;
}

function parameterLines(doc: JsonObject, parameters: JsonValue[]): string[] {
  const groups = new Map<string, string[]>();

  for (const value of parameters) {
    const parameter = resolve(doc, value);
    const name = asString(parameter?.name);
    if (!parameter || !name) continue;

    const location = asString(parameter.in) ?? "query";
    const flags = [typeName(doc, resolve(doc, parameter.schema))];
    if (parameter.required === true) flags.push("required");
    const description = asString(parameter.description);

    const group = groups.get(location) ?? [];
    group.push(
      `- \`${name}\` (${flags.join(", ")})${
        description ? ` — ${inline(description)}` : ""
      }`,
    );
    groups.set(location, group);
  }

  const lines: string[] = [];
  for (const [location, group] of groups) {
    lines.push(
      "",
      `### ${location[0].toUpperCase()}${location.slice(1)} parameters`,
      "",
      ...group,
    );
  }

  return lines;
}

function securityLines(doc: JsonObject, operation: JsonObject): string[] {
  const requirements = asArray(operation.security ?? doc.security);
  if (requirements.length === 0) return [];

  const components = resolve(doc, doc.components);
  const schemes = isObject(components?.securitySchemes)
    ? components.securitySchemes
    : {};
  const lines: string[] = [];

  for (const requirement of requirements) {
    if (!isObject(requirement)) continue;

    for (const name of Object.keys(requirement)) {
      const scheme = resolve(doc, schemes[name]);
      const type = asString(scheme?.type) ?? "unknown";
      const location = asString(scheme?.in);
      const header = asString(scheme?.name);

      lines.push(
        `- \`${name}\` (${type}${location ? `, in ${location}` : ""}${
          header && header !== name ? `, as \`${header}\`` : ""
        })`,
      );
    }
  }

  return lines.length > 0 ? ["", "### Authentication", "", ...lines] : [];
}

function operationLines(
  doc: JsonObject,
  heading: string,
  pathItem: JsonObject,
  operation: JsonObject,
  /** page title, to avoid repeating it as the operation summary */
  title?: string,
): string[] {
  const lines = [`## ${heading}`];

  const servers = asArray(operation.servers ?? pathItem.servers ?? doc.servers);
  const baseUrl = asString(resolve(doc, servers[0])?.url);
  if (baseUrl) lines.push("", `Base URL: \`${baseUrl}\``);

  const operationId = asString(operation.operationId);
  if (operationId) lines.push("", `Operation ID: \`${operationId}\``);
  if (operation.deprecated === true) lines.push("", "**Deprecated.**");

  const summary = asString(operation.summary);
  if (summary && summary.trim() !== title?.trim()) lines.push("", summary);

  const description = asString(operation.description);
  if (description) lines.push("", description);

  lines.push(...securityLines(doc, operation));
  lines.push(
    ...parameterLines(doc, [
      ...asArray(pathItem.parameters),
      ...asArray(operation.parameters),
    ]),
  );

  const requestBody = resolve(doc, operation.requestBody);
  if (requestBody) {
    lines.push(
      "",
      `### Request body${requestBody.required === true ? " (required)" : ""}`,
    );

    const bodyDescription = asString(requestBody.description);
    if (bodyDescription) lines.push("", bodyDescription);
    lines.push(...contentLines(doc, requestBody.content));
  }

  const responses = isObject(operation.responses)
    ? operation.responses
    : undefined;
  if (responses) {
    lines.push("", "### Responses");

    for (const [status, value] of Object.entries(responses)) {
      const response = resolve(doc, value);
      const responseDescription = asString(response?.description);

      lines.push(
        "",
        `#### ${status}${
          responseDescription ? ` — ${inline(responseDescription)}` : ""
        }`,
      );
      lines.push(...contentLines(doc, response?.content));
    }
  }

  return lines;
}

function parseRefs<T>(raw: string, attribute: string): T[] {
  const match = raw.match(new RegExp(`${attribute}=\\{(\\[[^\\]]*\\])\\}`));
  if (!match) return [];

  try {
    const parsed: unknown = JSON.parse(match[1]);
    return Array.isArray(parsed) ? (parsed as T[]) : [];
  } catch {
    return [];
  }
}

/**
 * Render the operations referenced by a generated OpenAPI page to Markdown.
 *
 * @param raw the unprocessed MDX source of the page
 * @param title the page title, skipped when an operation summary repeats it
 * @returns the Markdown body, or `undefined` if the page isn't an OpenAPI page
 */
export async function getOpenAPIText(
  raw: string,
  title?: string,
): Promise<string | undefined> {
  const documentId = raw.match(/document=["']([^"']+)["']/)?.[1];
  if (!documentId) return undefined;

  const operations = parseRefs<OperationRef>(raw, "operations");
  const webhooks = parseRefs<WebhookRef>(raw, "webhooks");
  if (operations.length === 0 && webhooks.length === 0) return undefined;

  const { bundled } = await openapi.getSchema(documentId);
  const doc = bundled as unknown as JsonObject;
  const lines: string[] = [];

  for (const { path, method } of operations) {
    const pathItem = resolve(
      doc,
      isObject(doc.paths) ? doc.paths[path] : undefined,
    );
    const operation = resolve(doc, pathItem?.[method.toLowerCase()]);
    if (!pathItem || !operation) continue;

    if (lines.length > 0) lines.push("");
    lines.push(
      ...operationLines(
        doc,
        `${method.toUpperCase()} ${path}`,
        pathItem,
        operation,
        title,
      ),
    );
  }

  for (const { name, method } of webhooks) {
    const pathItem = resolve(
      doc,
      isObject(doc.webhooks) ? doc.webhooks[name] : undefined,
    );
    const operation = resolve(doc, pathItem?.[method.toLowerCase()]);
    if (!pathItem || !operation) continue;

    if (lines.length > 0) lines.push("");
    lines.push(
      ...operationLines(
        doc,
        `${method.toUpperCase()} ${name} (webhook)`,
        pathItem,
        operation,
        title,
      ),
    );
  }

  return lines.length > 0 ? lines.join("\n") : undefined;
}
